" Arquivo: Configurações vim
" Criado: Qui 07/Jul/2011 hs 19:42
" Last Change: 2011 Jul 14 01:08:11
" Autor: Rafael V. dos Santos
" Site: 
" Twitter: @geekquilibrium

" Geral
  set nocompatible
  set backspace=indent,eol,start
  set history=1000
  set showcmd
  set showmode
  set incsearch
  set ignorecase
  set hlsearch
  set number
  set showbreak=...
  set wrap linebreak nolist
  set linespace=4
  set visualbell t_vb=
  set guioptions-=T
  set guioptions-=m
  set foldmethod=indent
  set foldnestmax=3
  set nofoldenable
  set wildmode=list:longest
  set wildmenu
  set wildignore=*.o,*.obj,*~
  set formatoptions-=o
  set scrolloff=3
  set sidescrolloff=7
  set sidescroll=1
  set mouse=a
  set hidden
  set laststatus=2
  set linespace=4
  set cursorline
  set background=light
  set guifont=Monaco

  filetype off
  filetype plugin on
  filetype indent on
  syntax on
  
  colorscheme github

" Statusline
  set stl+=\[FILE=%{&ff}\|%{&enc}\|%Y\|%t]
  set stl+=\[POS=%l,%c\|%L\|%P]
  set stl+=\[ASCII=%03.3b]
  set stl+=\[HEX=%02.2B]
  set stl+=\[GIT=%{GitBranch()}]
  set stl+=\[F=%{foldlevel('.')}]

" Pathogen
  call pathogen#runtime_append_all_bundles()
  call pathogen#helptags()

" Configurações dos plugins
  source $HOME/.vim/config/plugins.vim

" Funções vim
  source $HOME/.vim/config/funcoes.vim

" Source's Languages
   autocmd BufNewFile,BufRead *.rb source $HOME/.vim/config/rubyrc.vim
   autocmd BufNewFile,BufRead *.py source $HOME/.vim/config/pythonrc.vim
   autocmd BufNewFile,BufRead *.php,*.css source $HOME/.vim/config/phprc.vim
   autocmd BufNewFile,BufRead *.html,*.js,*.css,*.xml,*.scss source $HOME/.vim/config/webrc.vim

  " VIM,SHELL
    autocmd BufNewFile,BufRead *.vim,*.sh,*.txt setlocal ai et sta sw=2 ts=2 st=2 sts=2 tw=86 cc=+2
    autocmd Filetype vim,sh setlocal ai et sta sw=2 ts=2 st=2 sts=2 tw=86 cc=+2
    autocmd BufWritePost *.sh !bash -n <afile>
